### ISSUE TITLE
NoSuchMethodError when used in a project built with assertj-core 3.23.1

### ISSUE THREAD

**Issue by derelbenkoenig** [ngeor/yak4j-spring-test-utils#24]
it looks like in this project the POM declares assertj-core as a dependency but doesn't require a specific version. Another project depending on this (at 0.22.0 or 0.22.1) has failures in tests that occur when it tries to call the `.satisfies(Consumer)` method:
  
```
java.lang.NoSuchMethodError: 'org.assertj.core.api.AbstractAssert org.assertj.core.api.ObjectAssert.satisfies(java.util.function.Consumer)'
```

Is there a need for this project _not_ to specify a version for assertj-core in its dependencies? I built locally on my machine adding `<version>3.23.0</version>`, installed it into my local maven directory and built the other project with that, and it fixed the issue. I could open a PR adding the version to the POM if that would be acceptable

**Comment by ngeor** [comment]
Hi,

There's a parent pom mentioned here https://github.com/ngeor/yak4j-spring-test-utils/blob/trunk/pom.xml#L4
And that in turn specifies the version https://github.com/ngeor/java/blob/trunk/pom.xml#L70

NoSuchMethodError and similar messages are typically indicating "dependency hell", various dependencies pulling in conflicting versions of the same dependency. You can find information on the internet on how to troubleshoot that for your  project.

**Comment by derelbenkoenig** [comment]
Ah thanks, I didn't notice the version declared in the parent pom. That helps
